version: '3.9'

services: 
  cache: 
    image: redis:7-alpine
    container_name: cache
    restart: always
    ports:
      - 6379:6379
  
  api:
    build: .
    container_name: cep_api
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - cache
    depends_on:
      - cache

